### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Takahashi0502** [progate-bigin/furima-29263#10]
| 項目 | 備考 |
| ---- | ---- |
| フリマアプリURL | https://furima-29263.herokuapp.com/ |
| Basic認証ID | admin |
| Basic認証pass | master2382 |
| 出品者メール | test@test01.com |
| 出品者パス | test01 |
| 購入者メール | test@test02.com |
| 購入者パス | test02 |
| 購入用カードの番号 | 4242424242424242 |
| 購入用カードの期限 | 12/20 |
| 購入用カードのセキュリティコード | 123 |

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
